title: "HPC Engineering PoliMI - University Notes"
description: "This archive contains my notes while pursuing my master's degree in High Performance Computing Engineering at Politecnico di Milano."
show_downloads: false
google_analytics: UA-${{ secrets.GOOGLE_ANALYTICS }}
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
